name: Metrics

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.isocalendar.svg

          token: ${{ secrets.METRIC_TOKEN_GRAPH }}

          base: ""

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
